services:
  django:
    build:
      context: .
    container_name: sca_api
    env_file:
      - api.production.env
    depends_on:
      - db
    expose:
      - 8000
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production

  nginx:
    image: nginx:1.23.2
    container_name: nginx
    volumes:
      - ./django.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    depends_on:
      - django
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:15-bullseye
    restart: unless-stopped
    env_file:
      - db.production.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  pg_data: